config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  devise_for :users
  
  resources :users
  resources :examinations

  namespace :admin do
    root                'static_pages#home'
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  scope :correct, ->{where(correct: true).first}

end

app/models/answer_sheet.rb
class AnswerSheet < ActiveRecord::Base
  belongs_to :examination
  belongs_to :question
  belongs_to :answer

  scope :correct, ->{where correct: true}

end

app/models/examination.rb
class Examination < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user
  has_many :answer_sheets
  has_many :questions, through: :answer_sheets
  has_many :answers, through: :answer_sheets

  accepts_nested_attributes_for :answer_sheets

  before_update :update_score

  scope :in_order, ->(user){where("user_id = ?", user.id).order("created_at desc")}

  private

  def update_score
    score = 0
    results = self.answer_sheets
    results.each do |result|
      if result.answer.present? && result.answer.correct
        result.correct = true
        score = score + 1
      end
    end
    self.number_correct = score
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :subject
  has_many :answers, dependent: :destroy

  scope :create_questions, ->(subject){where("subject_id = ?", subject.id).limit(subject.number_questions).order("RAND()")}                             

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :examinations, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :examinations
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < AdminController
  def home
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user! 
  before_action :require_admin!

  private

    def require_admin!
      unless current_user.admin?
        sign_out current_user
        redirect_to admin_root_path
        return false
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  before_action :authenticate_user!

  def show
    @exam = Examination.find params[:id]
    @subject = @exam.subject
  end

  def index
    @exam = Examination.new
    @examinations = Examination.in_order(current_user) 
  end

  def create
    @subject = Subject.find params[:subject_id]
    @exam = @subject.examinations.new exam_params
    ids = Question.create_questions(@subject).pluck(:id)
    @exam.question_ids = ids
    if @exam.save
      redirect_to edit_examination_path @exam
    else
      render 'new'
    end
  end

  def edit
    @exam = Examination.find params[:id]
    @subject = @exam.subject
    @end = @exam.created_at + 20*60
  end

  def update
    @exam = Examination.find params[:id]
    @answer_sheets = @exam.answer_sheets
    if @exam.update_attributes answer_sheet_params
      redirect_to examination_path @exam
    else
      flash.now[:danger] = "Cannot submit"
    end
  end

  private
    def exam_params
      params.require(:examination).permit :user_id
    end

    def answer_sheet_params
      params.require(:examination).permit answer_sheets_attributes: [:id, :answer_id, :correct]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find params[:id]
    unless @user == current_user
      redirect_to :back, alert: "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Test Application"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


    # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find params[:id]
    redirect_to(root_url) unless current_user?(@user)
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  #Returns true if the user is admin, false otherwise
  def admin?
    current_user.admin == true
  end

  def logged_in_admin
    if !logged_in? || (logged_in? && !admin?)      
      store_location
      flash[:danger] = "Please log in."
      redirect_to admin_login_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Test App", admin_root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", admin_root_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/admin/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Admin Panel</h1><br/>
</div>

app/views/examinations/_form.html.erb
<span><% i=0 %>
<%= f.fields_for :answer_sheets do |builder| %>
  <p>
    <%= i=i+1 %>
    <%= builder.object.question.content %>
  </p>
  <% builder.object.question.answers.shuffle.each do |answer| %>
    <p>
      <%= builder.radio_button :answer_id, answer.id %>
      <%= builder.label :answer_id, answer.content %>
    </p> 
  <% end %>
  <br/>
<% end %>
</span>

app/views/examinations/edit.html.erb
<% provide(:title, "Start new test") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>
      <%= @subject.content %>
    </h1>
    <div class="countdown">
      Time left: <span id="clock"></span>
    </div>
    <div class="exam">
      <%= form_for @exam do |f| %>
        <%= render partial: 'form', locals: {:f=>f} %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#clock').countdown("<%= @end %>").on('update.countdown', function(event) {
    var $this = $(this).html(event.strftime(''
      + '<span>%M</span> min '
      + '<span>%S</span> sec'));
    }).on('finish.countdown', function(event) {
    $(document).ready(function(){
      $("#edit_examination_<%= @exam.id %>").submit();
    }); 
  });
</script>

app/views/examinations/index.html.erb
<% provide(:title, 'All examinations') %>
<div class="row">
  <div class="col-md-12">
    <div class="examinations">      
      <section>
        <%= form_for @exam do |f| %>
          <%= select_tag :subject_id, options_from_collection_for_select(Subject.all, :id, :content), {prompt: "Select a subject"} %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "Start", class: "btn btn-primary" %>
        <% end %>
      </section>
        <table class="table table-hover">
          <tr>
            <th>Date</th>
            <th>Subject</th>
            <th>Score</th>
            <th></th>
          </tr>
          <% @examinations.each do |exam| %>
            <tr>
              <td width="35%"><%= exam.created_at.strftime("%A, %d %B %Y at %I:%M%p") %></td>
              <td width="25%"><%= exam.subject.content %></td>
              <td width="25%"><%= exam.number_correct %></td>
              <td width="15%"><%= link_to "View", examination_path(exam) %></td>
            </tr>
          <% end %>
        </table>
      </div>        
    </div>
  </div>

app/views/examinations/show.html.erb
<% provide(:title, "Answers Sheet") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>
      <%= @subject.content %>
      <%= @exam.number_correct %>/20
    </h3>
    <div class="exam">
      <%= form_for @exam do |f| %>
        <span><% i=0 %>
          <%= f.fields_for :answer_sheets do |answer_sheet| %>
            <p>
              <%= i=i+1 %>
              <%= answer_sheet.object.question.content %>
            </p>
            <% answer_sheet.object.question.answers.each do |answer| %>
              <p>
                <%= answer_sheet.radio_button :answer_id, answer.id, disabled: true %>
                <%= answer_sheet.label :answer_id, answer.content %>
              </p> 
            <% end %>
            <% if answer_sheet.object.correct %>
              <p class="correct">Correct!</p>
            <% end %>
            <br/>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Test Application by Thuy Anh
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Test App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to 'Settings', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'admin/layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <script type="text/javascript">
    window.location.href="<%= examinations_path %>"
  </script>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Test App</h1><br/>
    <%= link_to "Sign up now!", new_user_registration_path , class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :full_name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>    
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', object: f.object  %>
      <%= f.label :full_name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <div class="row">
    <aside class="col-md-4">
      <section>
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  <div class="col-md-8">
    <h3>Profile </h3>
    <ul>
      <li>Full name: <%= @user.name %></li>
      <li>Email: <%= @user.email %></li>
    </ul>
  </div>
</div>